name: Auto Update version.json

on:
  release:
    types: [published]

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate version.json
        run: |
          VERSION=${{ github.event.release.tag_name }}
          APK_URL=${{ github.event.release.assets[0].browser_download_url }}
          NOTES="${{ github.event.release.body }}"

          echo "{
            \"versionName\": \"$VERSION\",
            \"apkUrl\": \"$APK_URL\",
            \"changelog\": [\"$NOTES\"]
          }" > version.json

      - name: Commit new version.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add version.json
          git commit -m "Auto update version.json"
          git push
